import type { PrismaClient } from '@prisma/client';
import type {
  User,
  UserRole,
  SubscriptionTier,
  Deployment,
  DeploymentStatus,
  Product,
  ProductStatus,
  ProductAccessLevel,
  ProductLicenseType,
  AgentFeedback,
  Review,
  Purchase,
  Earning,
  Notification,
  NotificationType,
  AgentMetrics,
  AgentLog,
  File,
  Workflow,
  WorkflowExecution,
  WorkflowSchedule,
  WorkflowTrigger,
  WorkflowVersion,
  WorkflowWebhook,
  Rating,
  Webhook
} from '@prisma/client';

export type {
  PrismaClient,
  User,
  UserRole,
  SubscriptionTier,
  Deployment,
  DeploymentStatus,
  Product,
  ProductStatus,
  ProductAccessLevel,
  ProductLicenseType,
  AgentFeedback,
  Review,
  Purchase,
  Earning,
  Notification,
  NotificationType,
  AgentMetrics,
  AgentLog,
  File,
  Workflow,
  WorkflowExecution,
  WorkflowSchedule,
  WorkflowTrigger,
  WorkflowVersion,
  WorkflowWebhook,
  Rating,
  Webhook
};

export const prisma = new PrismaClient(); 